# Generated by Django 5.1.6 on 2025-02-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_project_image_alter_technology_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_url',
            field=models.URLField(blank=True),
        ),
    ]
